### ISSUE TITLE
[BUG] @language field applied to non-literal properties

### ISSUE THREAD

**Issue by Abejithp** [Islandora/jsonld#82]
I am experiencing an issue when using the owl:sameAs property with the language field in RDF/JSON-LD, causing failure during indexing into Blazegraph. According to RDF, OWL, and JSON-LD specifications, the language field is only valid for literals, not URIs. From my current understanding during the normalization of the field items, the language field is added regardless of whether it is literal. For context, the line I'm referring to can be found here: [FieldItemNormalizer.php](https://github.com/Islandora/jsonld/blob/3.x/src/Normalizer/FieldItemNormalizer.php#L108)

**What steps does it take to reproduce the issue?**
1. Create a taxonomy term that utilizes the owl:sameAs property
2. Attempt to index this newly created term

**Expected Behaviour:** The taxonomy term should be properly indexed and inserted into Blazegraph.
**Actual Behaviour:** The taxonomy term is not able to be indexed and inserted into Blazegraph.

**Screenshots:**
The following screenshots illustrate the current behaviour, showing the language field included within the owl:sameAs property:

![jsonld_lang](https://github.com/user-attachments/assets/42244ffa-f4be-4746-8e95-ae4766ee949a)
![jsonld_fail](https://github.com/user-attachments/assets/cf9e9683-3ef2-4ddf-833e-a1986051351e)
![jsonld_msg](https://github.com/user-attachments/assets/7687ccb9-fb56-4b07-a5c0-73aa02e3adb7)

The following screenshots demonstrate the behaviour after removing the language field from the owl:sameAs property, which allows successful indexing:
![jsonld_nolang](https://github.com/user-attachments/assets/c9e2ce1d-4e97-4fdd-b4d6-e54594dee317)
![jsonld_success](https://github.com/user-attachments/assets/f032a324-bddc-4f85-b37c-420fa827d822)

Please let me know if there are any further details required to assist in resolving this issue.

**Comment by seth-shaw-asu** [comment]
I took a few minutes to try and reproduce on the sandbox, but couldn't. See https://sandbox.islandora.ca/taxonomy/term/886?_format=jsonld.
Could you provide the field configuration and the RDF configuration for the content type? That might help us debug?

Also the deployment method used (e.g. the ISLE-DC starter site plus version) might be helpful.

**Comment by Abejithp** [comment]
After reviewing the JSON-LD you provided, we identified that the issue was related to our JSON-LD configuration. We have now resolved the issue. Thank you again for your help in investigating this. I will go ahead and close this issue.
